apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-recycle-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-recycle-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-recycle-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-recycle-controller
subjects:
- kind: ServiceAccount
  name: pod-recycle-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-recycle-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-recycle-controller
  template:
    metadata:
      labels:
        app: pod-recycle-controller
    spec:
      serviceAccountName: pod-recycle-controller
      containers:
      - name: controller
        image: 231054688549.dkr.ecr.us-west-2.amazonaws.com/pod-recycle-controller:latest
        imagePullPolicy: Always
